{% set name = "jenn" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jenn-{{ version }}.tar.gz
  sha256: d4e6f8299e49018e5c1b5c4a2ef2c0db5fc42bf73c71f31ef182b3def0b51fe4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - orjson >=3.9
    - jsonpointer >=2.4
    - jsonschema >=4.22
    - matplotlib

test:
  imports:
    - jenn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shb84/JENN.git
  summary: Jacobian-Enhanced Neural Nets (JENN)
  license: MIT
  license_file: LICENSE
  description: |
    Jacobian-Enhanced Neural Networks (JENN) are fully connected 
    multi-layer perceptrons, whose training process is modified to 
    predict partial derivatives accurately. The main benefit of 
    is better accuracy with fewer training points compared to 
    standard fully connected neural nets.
  doc_url: https://shb84.github.io/JENN/
  dev_url: https://github.com/shb84/JENN.git
  doc_source_url: https://github.com/shb84/JENN/blob/master/docs/source/

extra:
  recipe-maintainers:
    - shb84
