{% set name = "jenn" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jenn-{{ version }}.tar.gz
  sha256: 2c0e07bc3ce04897d9ffdbaccfe7e0f434e2251dba137d7cbe79f06d9a0f4705

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - orjson >=3.9
    - jsonpointer >=2.4
    - jsonschema >=4.22
    - matplotlib

test:
  imports:
    - jenn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shb84/JENN.git
  summary: Jacobian-Enhanced Neural Nets (JENN)
  license: MIT
  license_file: LICENSE
  description: |
    Jacobian-Enhanced Neural Networks (JENN) are fully connected 
    multi-layer perceptrons, whose training process is modified to 
    predict partial derivatives accurately. The main benefit of 
    is better accuracy with fewer training points compared to 
    standard fully connected neural nets.
  doc_url: https://shb84.github.io/JENN/
  dev_url: https://github.com/shb84/JENN.git
  doc_source_url: https://github.com/shb84/JENN/blob/master/docs/source/

extra:
  recipe-maintainers:
    - shb84
