{% set name = "jenn" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jenn-{{ version }}.tar.gz
  sha256: a98bcf0609bbac6f565b4bad271ff51fc5e9cf0e73b49649a80e444e100710cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.22
    - orjson >=3.9
    - jsonpointer >=2.4
    - jsonschema >=4.22

test:
  imports:
    - jenn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/shb84/JENN.git
  summary: Jacobian-Enhanced Neural Nets (JENN)
  license: MIT
  license_file: LICENSE
  description: |
    Jacobian-Enhanced Neural Networks (JENN) are fully connected 
    multi-layer perceptrons, whose training process is modified to 
    predict partial derivatives accurately. The main benefit of 
    is better accuracy with fewer training points compared to 
    standard fully connected neural nets.
  doc_url: https://shb84.github.io/JENN/
  dev_url: https://github.com/shb84/JENN.git
  doc_source_url: https://github.com/shb84/JENN/blob/master/docs/source/

extra:
  recipe-maintainers:
    - shb84
